- name: service nginx script
  copy: 
    src: nginx.service  
    dest: /lib/systemd/system/nginx.service
- name: start nginx service
  systemd: 
    name: nginx 
    state: started 
    enabled: yes
