- name: copy docker to remote ubuntu22.04
  copy: 
    src: docker/
    dest: /usr/bin/
    mode: u+x
- name: copy docker-compose to remote ubuntu22.04
  copy: 
    src: docker-compose
    dest: /usr/local/sbin/
    mode: u+x
