- name: create docker group
  group: 
    name: docker
    state: present
    gid: "{{ gid }}"

- name: copy docker to remote ubuntu22.04
  copy: 
    src: docker/
    dest: /usr/bin/
    mode: u+x

- name: copy docker-compose to remote ubuntu22.04
  copy: 
    src: docker-compose
    dest: /usr/local/sbin/
    mode: u+x

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/docker
    state: directory
- name: docker daemon.json
  copy: 
    src: daemon.json 
    dest: /etc/docker/daemon.json

- name: service containerd.service script
  copy: 
    src: containerd.service 
    dest: /lib/systemd/system/containerd.service
- name: service docker script
  copy: 
    src: docker.service  
    dest: /lib/systemd/system/docker.service
- name: service docker.socket
  copy: 
    src: docker.socket 
    dest: /lib/systemd/system/docker.socket
- name: start containerd.service
  systemd: 
    name: containerd.service
    state: started 
    enabled: yes
- name: start docker.socket
  systemd: 
    name: docker.socket
    state: started 
    enabled: yes
- name: start docker service
  systemd: 
    name: docker.service 
    state: started 
    enabled: yes

